services:
  r10-kangaroo-dist:
    build: .
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "${PORT:-9999}:9999"
    entrypoint: /etc/init.sh
    init: true
    restart: unless-stopped
